### ISSUE TITLE
Publish sources JAR and javadoc JAR

### ISSUE THREAD

**Issue by ceefour** [imgix/imgix-java#19]
Please also publish sources JAR and javadoc JAR, not just binary JAR.

In Maven you simply do `source:jar javadoc:jar` before `deploy`. Should have same feature in Gradle.

Thank you.

**Comment by esetnik** [comment]
@ceefour thanks for reporting this I just faced the same issue

**Comment by zacman85** [comment]
This has been corrected in version 1.1.10. Thanks for the heads up.
