### ISSUE TITLE
path params to createURL does not support folder structure

### ISSUE THREAD

**Issue by pallavrustogi** [imgix/imgix-java#20]
This use case arises when we pass in the path URI which contains /, createURL converts them to %2F which breaks the URL. Example, builder.createURL("photos/x1/abc.jpg", params). This spits out the URL as http://domain/photos%2Fx1%2Fabc.jpg?{params}

**Comment by simonkuhn** [comment]
This was resolved by #21 and is available in the 1.1.9 release: https://github.com/imgix/imgix-java/releases/tag/1.1.9
