### ISSUE TITLE
version 1.1.11 is NOT mirrored to jcenter

### ISSUE THREAD

**Issue by shiroyama** [imgix/imgix-java#24]
I followed the README and realized the version number written now is not mirrored to jcenter.

```
compile "com.imgix:imgix-java:1.1.11"
```

I checked the jcenter website and found ver 1.1.10, and only that version is mirrored to jcenter.
https://bintray.com/imgix/maven/imgix-java

thanks.

**Comment by feresr** [comment]
is this library still being maintained?

**Comment by hashknot** [comment]
Hi @feresr, updates to the library are in pipeline. I will get the latest version published to bintray soon. I will keep you posted. Thanks!

**Comment by hashknot** [comment]
@feresr, @shiroyama v1.1.11 has been published. Can you guys confirm so that I can close this issue?

**Comment by shiroyama** [comment]
@hashknot confirmed! working great! thank you👍

**Comment by hashknot** [comment]
Thank you, @shiroyama!
