### ISSUE TITLE
Library; not included in Android: javax.xml.bind

### ISSUE THREAD

**Issue by feresr** [imgix/imgix-java#27]
Hi! first of all, thanks for this great library.

I'm trying to implement ImgIx on android app and I'm getting the following warning:

```Invalid package reference in library; not included in Android: javax.xml.bind. Referenced from com.imgix.URLHelper. ```

I tried adding this rule to proguard without success

`-dontwarn javax.xml.**`

**Comment by feresr** [comment]
I "fixed" the issue by adding a lint ignore exception 

```
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright 2016 Canva Inc. All Rights Reserved. -->

<lint>
  <issue id="InvalidPackage">
    <ignore regexp="javax.xml.bind.*"/>
  </issue>
</lint>
```

Not sure why this is required, is there a better way?

**Comment by hashknot** [comment]
Thank you for letting us know, @feresr!

Apparently `javax` packages aren't available on Android and the javax classes used by imgix-java have been removed in Java 10. I will cut a new release next week some time which should take care of this problem.

I will keep you posted.

**Comment by hashknot** [comment]
@feresr I published v1.1.12. Can you confirm if you're still running into this problem?

**Comment by feresr** [comment]
Will confirm first thing Monday :) thanks for the assistance guys!

**Comment by hashknot** [comment]
Hi @feresr, did you get a chance to test v1.1.12?

**Comment by feresr** [comment]
Hi @hashknot, I did, this is not an issue anymore, thanks for the fix! 🎉
