### ISSUE TITLE
Put jar in Maven Central

### ISSUE THREAD

**Issue by stickfigure** [imgix/imgix-java#4]

**Comment by kellysutton** [comment]
Alright, I'm running into a few issues getting this published on Maven central. Can you paste in some commands to run? The one that keeps happening looks to be a permissions issue:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.1:prepare (default-cli) on project imgix: Unable to commit files
```

I've triple-checked permissions on our end, and my local client has push capabilities. Any ideas?

**Comment by stickfigure** [comment]
The only commands I use to upload a release are `mvn release:prepare; mvn release:perform`.

My ~/.m2/settings.xml looks like this:

```
<settings>
    <servers>
        <server>
            <id>ossrh</id>
            <username>my-username</username>
            <password>my-password</password>
        </server>
    </servers>

    <profiles>
        <profile>
            <id>ossrh</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <gpg.passphrase>my-gpg-passphrase</gpg.passphrase>
            </properties>
        </profile>
    </profiles>
</settings>
```

**Comment by goldensunliu** [comment]
+1

**Comment by kellysutton** [comment]
Heard loud and clear. We'll give this another try on our end!

**Comment by yayitswei** [comment]
+1 please

**Comment by paulstraw** [comment]
Hey @yayitswei, I'm going to get this sorted out this week. :grin:

**Comment by paulstraw** [comment]
I'm working on getting this into the Central. I've [filed a ticket](https://issues.sonatype.org/browse/OSSRH-20281) with OSSRH to get it added on their end so I can actually publish it.

**Comment by matthurne** [comment]
You might consider Bintray jCenter instead of or in addition to Maven Central. We've found it a fair bit easier to work with.

**Comment by matthurne** [comment]
If you want to pursue publishing to jCenter _and_ switch to Gradle, you might find the build.gradle and README in this project a useful reference: https://github.com/commercehub-oss/dropwizard-mongo

**Comment by eboto** [comment]
@paulstraw it looks like that OSSRH ticket went through. Did you ever end up publishing the artifact?

**Comment by forrestbice** [comment]
@paulstraw and @kellysutton any news on getting this to Maven or JCenter?

**Comment by paulstraw** [comment]
Unfortunately not @forrestbice. We've tried publishing to Maven several times with varying degrees of non-success. I'll investigate JCenter.

**Comment by forrestbice** [comment]
@paulstraw thanks for the speedy response and for taking another look at this, it'd be awesome to get this in JCenter which is actually preferred over Maven. Let me know if I can be of assistance. Would love to include this in my company's Android project without having to build my own Jar

**Comment by forrestbice** [comment]
@paulstraw this looks like a nice guide and in fact it appears you'll only need to follow `Step 1` of the `How to upload your library to jcenter` section: https://inthecheesefactory.com/blog/how-to-upload-library-to-jcenter-maven-central-as-dependency/en

**Comment by paulstraw** [comment]
Very cool @forrestbice, I'll take a look at that shortly! Appreciate the help 👌

**Comment by forrestbice** [comment]
Awesome! And actually I jumped the gun on my advice. The tutorial outlines a 7 step process and you can simply skip steps 2 and 3 if you don't plan to upload to Maven and only plan to upload to JCenter which seems fine; Android Studio default repository is now JCenter instead of Maven

**Comment by paulstraw** [comment]
![screen-shot-2016-09-02-15-16-28](https://cloud.githubusercontent.com/assets/117288/18219675/6233f92e-7120-11e6-9a7f-11e0a4d8df07.png)

Progress, I think? Though unfortunately that notification doesn't give any next steps. I'm hoping they'll email me?

**Comment by forrestbice** [comment]
@paulstraw which step of the guide I liked to are you on?

**Comment by paulstraw** [comment]
@forrestbice That guide is unfortunately a bit dated. I ended up first switching the entire project over to Gradle, then following the directions here: https://github.com/bintray/gradle-bintray-plugin

I believe things are just pending inclusion into the [JCenter repository](https://bintray.com/bintray/jcenter) now.

**Comment by forrestbice** [comment]
Ah ok cool, looks like I found it here: https://bintray.com/imgix/imgix-java/imgix-java. Please let me know once you think it's been approved. Also if you need a good reference for a library that has been approved Butterknife is a good example https://bintray.com/bintray/jcenter/com.jakewharton%3Abutterknife

**Comment by paulstraw** [comment]
Previously, they messaged me pretty quickly when I was still trying to figure out how to publish. I'm assuming/hoping the same will be the case for when it's approved.

**Comment by asaarnak** [comment]
How it's going?

Just tested it out. https://bintray.com/imgix/maven/imgix-java/1.1.8
Could not find com.imgix:imgix-java:1.1.8.
  Searched in the following locations:
      https://repo1.maven.org/maven2/com/imgix/imgix-java/1.1.8/imgix-java-1.1.8.pom
      https://repo1.maven.org/maven2/com/imgix/imgix-java/1.1.8/imgix-java-1.1.8.jar
      https://jcenter.bintray.com/com/imgix/imgix-java/1.1.8/imgix-java-1.1.8.pom
      https://jcenter.bintray.com/com/imgix/imgix-java/1.1.8/imgix-java-1.1.8.jar

**Comment by paulstraw** [comment]
Alrighty! This has been approved and added to JCenter: https://bintray.com/imgix/maven/imgix-java

![Response from Bintray folks](https://paul.st/Ax5hz0/Screen-Shot-2016-09-13-10-55-53.png)

Should be good to go now. Thanks all for the patience!

**Comment by forrestbice** [comment]
@asaarnak `compile "com.imgix:imgix-java:1.1.8"` is working for me. @paulstraw thanks for all of your work on this! I'll open a PR to the README with updated install instructions. Note: Whenever there is a new release and subsequent push to Bintray could you please start tagging those releases so that developers can easily know they should be bumping the library on their/our end?

**Comment by paulstraw** [comment]
@forrestbice Awesome, looking forward to that PR. I'll definitely be tagging releases going forward.
