### ISSUE TITLE
Move from Bintray/JCenter to Maven Central

### ISSUE THREAD

**Issue by csummers** [imgix/imgix-java#64]
JFrog is shutting down JCenter.  Is there a plan to move this library to Maven Central?

Announcement here: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Relevant dates:

- 2021-03-31 - No new package versions after this date
- 2021-05-01 - REST API & UI shutdown
- 2022-02-01 - JCenter repo (downloads) shutdown

**Comment by ericdeansanchez** [comment]
Hey 👋 @csummers thanks for opening this issue. In short, yes. We aren't currently working on migrating from using Bintray/JFrog, but after looking at the approaching April 12th and May 1st deadlines I think we need to migrate ASAP.
